### ISSUE TITLE
zeus build error

### ISSUE THREAD

**Issue by devmdeniz** [melianmiko/ZeppOS-Tasks#28]
When i trying to run ``` zeus build ``` command, i got this error:
```
PS C:\xampp\htdocs\ZeppOS-NoteApp\NoteApp4> zeus build
? Which targets would you like to build? mi-band-7, mi-band-7-offline, balance, gts-4-mini, band-7, t-rex-ultra,
gtr-mini, gtr-4, gts-4, falcon, cheetah, cheetah-pro, gtr-3-pro, gtr-3, gts-3, t-rex-2
info  Start building package, targets: mi-band-7, mi-band-7-offline, balance, gts-4-mini, band-7, t-rex-ultra, gtr-mini, gtr-4, gts-4, falcon, cheetah, cheetah-pro, gtr-3-pro, gtr-3, gts-3, t-rex-2.
Error: The icon in app.json is empty or the image does not exist
    at C:\Users\USER\AppData\Roaming\npm\node_modules\@zeppos\zeus-cli\node_modules\@zeppos\zpm\lib\node.js:2:584390
    at Generator.next (<anonymous>)
    at C:\Users\USER\AppData\Roaming\npm\node_modules\@zeppos\zeus-cli\node_modules\@zeppos\zpm\lib\node.js:2:581828
    at new Promise (<anonymous>)
    at v (C:\Users\USER\AppData\Roaming\npm\node_modules\@zeppos\zeus-cli\node_modules\@zeppos\zpm\lib\node.js:2:581647)
    at K (C:\Users\USER\AppData\Roaming\npm\node_modules\@zeppos\zeus-cli\node_modules\@zeppos\zpm\lib\node.js:2:584290)
    at gs.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\@zeppos\zeus-cli\node_modules\@zeppos\zpm\lib\568.node.js:1:48971)
    at Generator.next (<anonymous>)
    at C:\Users\USER\AppData\Roaming\npm\node_modules\@zeppos\zeus-cli\node_modules\@zeppos\zpm\lib\568.node.js:1:46701
    at new Promise (<anonymous>)
```
```
error  TypeError: Cannot read properties of undefined (reading 'replace')
    at \npm\node_modules\@zeppos\zeus-cli\private-modules\zeppos-app-utils\dist\modules\build.js:156:44
    at step (npm\node_modules\@zeppos\zeus-cli\private-modules\zeppos-app-utils\dist\modules\build.js:56:23)
    at Object.next (\npm\node_modules\@zeppos\zeus-cli\private-modules\zeppos-app-utils\dist\modules\build.js:37:53)
    at fulfilled (\npm\node_modules\@zeppos\zeus-cli\private-modules\zeppos-app-utils\dist\modules\build.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

I chose the Amazfit band 7.

**Comment by melianmiko** [comment]
Please, check `README.md`.

```
Clone this project recursively:

git clone --recursive https://github.com/melianmiko/ZeppOS-Tasks.git
Then, you should build assets for all devices. To do that, run prepare_all.py script in that project dir.

python3 prepare_all.py
```

**Comment by devmdeniz** [comment]
now, i got 
```
PS C:\xampp\htdocs\ZeppOS-NoteApp\NoteApp4> py.exe .\prepare_all.py
Traceback (most recent call last):
  File "C:\xampp\htdocs\ZeppOS-NoteApp\NoteApp4\prepare_all.py", line 135, in <module>
    for f in (lib_assets / "screen_board").iterdir():
  File "C:\Users\GAME GARAJ\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1057, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\xampp\\htdocs\\ZeppOS-NoteApp\\NoteApp4\\lib\\mmk\\assets\\screen_board'
```
this error

**Comment by melianmiko** [comment]
...

```
git clone --recursive https://github.com/melianmiko/ZeppOS-Tasks.git
```
